# Generated by Django 4.1.13 on 2023-11-16 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentaddmodel',
            old_name='filetype',
            new_name='fileType',
        ),
    ]
