# Generated by Django 4.1.13 on 2023-11-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_rename_filetype_assignmentaddmodel_filetype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmentaddmodel',
            options={'verbose_name': 'AssignmentAddModel', 'verbose_name_plural': 'AssignmentAddModels'},
        ),
        migrations.RemoveField(
            model_name='assignmentaddmodel',
            name='fileType',
        ),
        migrations.AddField(
            model_name='assignmentaddmodel',
            name='fileype',
            field=models.CharField(default='', max_length=100),
        ),
    ]
