# Generated by Django 4.1.13 on 2023-11-16 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieadd',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='movieadd',
            name='distributor',
        ),
    ]
