# Generated by Django 4.1.13 on 2023-11-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAddModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('qualification', models.CharField(default='', max_length=100)),
                ('specialization', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('department', models.CharField(default='', max_length=100)),
                ('salary', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'DoctorAddModel',
                'verbose_name_plural': 'DoctorAddModels',
            },
        ),
    ]
