# Generated by Django 4.1.13 on 2023-11-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('pincode', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'PatientAdd',
                'verbose_name_plural': 'PatientAdds',
            },
        ),
    ]
